import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "black",
  },
  captureContainer: {
    flex: 1,
    backgroundColor: "#000",
  },
  camera: {
    flex: 1,
    justifyContent: "space-between",
  },
  overlayContainer: {
    flex: 1,
    justifyContent: "space-between",
    padding: 20,
    paddingTop: 50,
    paddingBottom: 40,
  },
  topControls: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  overlayCard: {
    backgroundColor: "rgba(0,0,0,0.5)",
    borderRadius: 20,
    padding: 12,
    marginHorizontal: 16,
    marginBottom: 30,
    marginTop: "auto",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.2)",
  },
  overlayHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 8,
  },
  appIconSmall: {
    width: 40,
    height: 40,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.3)",
  },
  dateTimeContainer: {
    backgroundColor: "rgba(255,255,255,0.2)",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
  },
  dateTimeText: {
    color: "white",
    fontWeight: "bold",
    fontSize: 14,
  },
  overlayBody: {
    flexDirection: "row",
    gap: 10,
    marginBottom: 10,
  },
  mapPreview: {
    width: 72,
    height: 72,
    borderRadius: 12,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.2)",
    backgroundColor: "#e0e0e0",
    justifyContent: "center",
    alignItems: "center",
  },
  mapImage: {
    width: "100%",
    height: "100%",
  },
  mapPinOverlay: {
    position: "absolute",
    top: 18,
    left: 28,
  },
  mapAttributionBadge: {
    position: "absolute",
    top: 2,
    left: 2,
    backgroundColor: "rgba(0,0,0,0.45)",
    borderRadius: 4,
    paddingHorizontal: 3,
    paddingVertical: 1,
    maxWidth: 75,
  },
  mapAttributionText: {
    color: "rgba(255,255,255,0.8)",
    fontSize: 7,
  },
  mapRefreshButton: {
    position: "absolute",
    top: 2,
    right: 2,
    width: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: "rgba(0,0,0,0.55)",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.25)",
  },
  addressBox: {
    flex: 1,
    justifyContent: "center",
    backgroundColor: "rgba(0,0,0,0.3)",
    borderRadius: 12,
    paddingHorizontal: 4,
    paddingVertical: 4,
    minHeight: 72,
  },
  addressTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 0,
  },
  addressSubRow: {
    marginTop: 0,
  },
  addressTickerContainer: {
    flex: 1,
    overflow: "hidden",
  },
  addressSingleLineText: {
    color: "white",
    fontWeight: "bold",
    fontSize: 11,
  },
  addressSingleLineSubText: {
    color: "#ddd",
    fontSize: 10,
  },
  locationErrorText: {
    color: "#FFD166",
    fontSize: 11,
    marginTop: 6,
  },
  overlayFooter: {
    flexDirection: "row",
    justifyContent: "center",
    flexWrap: "wrap",
    gap: 8,
  },
  pill: {
    backgroundColor: "rgba(255,255,255,0.2)",
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  pillText: {
    color: "white",
    fontSize: 11,
    fontWeight: "600",
  },
  controlsContainer: {
    height: 140,
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
    backgroundColor: "black",
    paddingBottom: 20,
  },
  controlButton: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: "rgba(255,255,255,0.1)",
    justifyContent: "center",
    alignItems: "center",
  },
  captureButtonOuter: {
    width: 84,
    height: 84,
    borderRadius: 42,
    backgroundColor: "rgba(255,255,255,0.3)",
    justifyContent: "center",
    alignItems: "center",
  },
  captureButton: {
    width: 70,
    height: 70,
    borderRadius: 35,
    backgroundColor: "white",
    shadowColor: "#fff",
    shadowOffset: {
      width: 0,
      height: 0,
    },
    shadowOpacity: 0.5,
    shadowRadius: 10,
    elevation: 5,
  },
  captureActive: {
    transform: [{ scale: 0.9 }],
    backgroundColor: "#ddd",
  },
  permissionContainer: {
    flex: 1,
    backgroundColor: "#111",
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
  },
  permissionText: {
    color: "#fff",
    fontSize: 18,
    textAlign: "center",
    marginBottom: 20,
    opacity: 0.8,
  },
  dualControls: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    backgroundColor: "rgba(0,0,0,0.3)",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
  },
  dualText: {
    color: "white",
    fontSize: 12,
    fontWeight: "600",
  },
  miniSwap: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: "rgba(255,255,255,0.2)",
    justifyContent: "center",
    alignItems: "center",
  },
  pipCameraContainer: {
    position: "absolute",
    top: 100,
    left: 20,
    width: 120,
    height: 160,
    borderRadius: 16,
    borderWidth: 2,
    borderColor: "white",
    overflow: "hidden",
    zIndex: 10,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.5,
    shadowRadius: 4,
    elevation: 5,
  },
  pipCamera: {
    flex: 1,
  },
});
