import { StyleSheet, Platform } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  content: {
    flex: 1,
    padding: 24,
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 40,
    marginTop: Platform.OS === "android" ? 40 : 0,
  },
  greeting: {
    fontSize: 16,
    color: "#B0B0E0",
    marginBottom: 4,
  },
  appName: {
    fontSize: 28,
    fontWeight: "bold",
    color: "white",
    letterSpacing: 0.5,
  },
  settingsButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: "rgba(255,255,255,0.1)",
    justifyContent: "center",
    alignItems: "center",
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "600",
    color: "white",
    marginBottom: 16,
    letterSpacing: 0.5,
  },
  modesContainer: {
    flexDirection: "row",
    gap: 16,
    marginBottom: 40,
  },
  modeCard: {
    flex: 1,
    height: 160,
    borderRadius: 24,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },
  modeGradient: {
    flex: 1,
    padding: 20,
    borderRadius: 24,
    justifyContent: "space-between",
  },
  iconCircle: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: "white",
    justifyContent: "center",
    alignItems: "center",
  },
  modeTitle: {
    fontSize: 20,
    fontWeight: "bold",
    color: "white",
    marginTop: 10,
  },
  modeSubtitle: {
    fontSize: 12,
    color: "rgba(255,255,255,0.9)",
    fontWeight: "500",
  },
  locationContainer: {
    flex: 1,
  },
  locationCard: {
    flex: 1,
    borderRadius: 24,
    overflow: "hidden",
    position: "relative",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.1)",
    backgroundColor: "rgba(0,0,0,0.2)",
  },
  mapIconHeader: {
    position: "absolute",
    top: 12,
    left: 12,
    zIndex: 2,
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(0,0,0,0.3)",
    alignSelf: "flex-start",
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
  },
  pulsingDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: "#00FF00",
    marginRight: 6,
  },
  liveText: {
    color: "#00FF00",
    fontSize: 10,
    fontWeight: "bold",
  },
  mapStatus: {
    ...StyleSheet.absoluteFillObject,
    alignItems: "center",
    justifyContent: "center",
  },
  mapStatusText: {
    marginTop: 10,
    color: "rgba(255,255,255,0.75)",
    fontSize: 12,
    textAlign: "center",
    paddingHorizontal: 16,
  },
  mapAttribution: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 2,
    alignItems: "center",
    zIndex: 2,
  },
  mapAttributionText: {
    fontSize: 9,
    color: "rgba(255,255,255,0.7)",
    backgroundColor: "rgba(0,0,0,0.35)",
    paddingHorizontal: 5,
    paddingVertical: 2,
    borderRadius: 5,
  },
  mapControls: {
    position: "absolute",
    right: 8,
    bottom: 8,
    alignItems: "center",
    zIndex: 2,
  },
  mapControlButton: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: "rgba(0,0,0,0.6)",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 6,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.2)",
  },
  mapControlButtonDisabled: {
    opacity: 0.65,
  },
  locationDetails: {
    position: "absolute",
    left: 10,
    bottom: 10,
    zIndex: 2,
    backgroundColor: "rgba(0,0,0,0.55)",
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.2)",
  },
  locationDetailsText: {
    color: "#fff",
    fontSize: 12,
    fontWeight: "600",
    lineHeight: 16,
  },
  locationDetailsMeta: {
    color: "rgba(255,255,255,0.8)",
    fontSize: 11,
    marginTop: 2,
  },
  locationWarning: {
    color: "#FFD166",
    fontSize: 11,
    marginTop: 3,
    maxWidth: 170,
  },
});
